### Arithmethic operators
Allows to increase or decrease color intensity via adding or subtracting matrix

In [2]:
import cv2
import numpy as np

img= cv2.imread('./Nature.jpeg')


In [15]:
# OpenCV uses unsigned 8-bit integer datatype to store image data
M = np.ones(img.shape, dtype="uint8") * 200

# while addition or subtraction make sure that values does not exceed the range (0-255)
# else it will convert to 0 for negative integer and 255 for value above 255
# and corresponding pixel will be white and black accordingly

add= cv2.add(img, M)
print("Image RGB component values: \n", img[:,:,2])
print("Image RGB component values after modifications (adding): \n", add[:,:,2])
cv2.imshow("Add", add)
cv2.waitKey()

subtract= cv2.subtract(img, M)
print("Image RGB component values after modifications (subtracting): \n", subtract[:,:,2])
cv2.imshow("Subtract", subtract)
cv2.waitKey()

cv2.destroyAllWindows()

Image RGB component values: 
 [[73 73 73 ... 80 64 98]
 [73 73 73 ... 69 56 95]
 [73 73 73 ... 64 52 92]
 ...
 [14  9  6 ... 87 22 18]
 [12  9  9 ... 24 19 38]
 [16 12 10 ... 41 24 14]]
Image RGB component values after modifications (adding): 
 [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 252 255]
 ...
 [214 209 206 ... 255 222 218]
 [212 209 209 ... 224 219 238]
 [216 212 210 ... 241 224 214]]
Image RGB component values after modifications (subtracting): 
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
