In [2]:
import cv2
import numpy as np

In [7]:
# Black sheet
black_sheet=np.zeros((500,500,3))
black_sheet_bw=np.zeros((500,500)) #for Gray Scale shapes
cv2.imshow('Blank sheet', black_sheet)
cv2.imshow('Blank sheet (B&W)', black_sheet_bw)
cv2.waitKey()
cv2.destroyAllWindows()

### Lines
cv2.line(image_variable, starting co-ordinates, ending co-ordinates, color, thickness)

In [34]:
black_sheet=np.zeros((500,500,3))
cv2.line(black_sheet, (100,50), (200,10), (255,0,120), 10)

cv2.imshow('Line', black_sheet)
cv2.waitKey()
cv2.destroyAllWindows()

### Rectangle
cv2.rectangle(image_variable, starting vertex, opposite vertex, color, thickness)

Note:
- thickness to be -1 to completely fill the shape

In [48]:
black_sheet=np.zeros((500,500,3))
cv2.rectangle(black_sheet, (100,250), (200,10), (100,0,100), -1)

cv2.imshow('Rectangle', black_sheet)
cv2.waitKey()
cv2.destroyAllWindows()

### Circle
cv2.circle(image_variable, center, radius, color, thickness)  
Note:

- thickness to be -1 to completely fill the shape

In [55]:
black_sheet=np.zeros((500,500,3))
cv2.circle(black_sheet, (280,150), 100, (0,3,100), -1)

cv2.imshow('Circle', black_sheet)
cv2.waitKey()
cv2.destroyAllWindows()

### Polygons
cv2.polylines(image_variable, [pts], isClosed, color, thickness)

Note:
- isClosed value is True then Closed figure and if it's False then Open Figure
- thickness to be -1 to completely fill the shape

In [79]:
black_sheet=np.zeros((500,500,3))
pts= np.array([[20,5],[350,50],[500,200]])
print(pts)
pts= pts.reshape((-1,1,2))
print(pts)
cv2.polylines(black_sheet, [pts], True, (0,230,100), 2)

cv2.imshow('Line', black_sheet)
cv2.waitKey()
cv2.destroyAllWindows()

[[ 20   5]
 [350  50]
 [500 200]]
[[[ 20   5]]

 [[350  50]]

 [[500 200]]]


### Text
cv2.putText(image_variable, 'Text to Display', bottom left starting point, Font, Font Size, Color, Thickness)  

Font Styles:
- FONT_HERSHEY_SIMPLEX, FONT_HERSHEY_PLAIN
- FONT_HERSHEY_DUPLEX,FONT_HERSHEY_COMPLEX 
- FONT_HERSHEY_TRIPLEX, FONT_HERSHEY_COMPLEX_SMALL
- FONT_HERSHEY_SCRIPT_SIMPLEX
- FONT_HERSHEY_SCRIPT_COMPLEX

In [76]:
black_sheet=np.zeros((500,500,3))
cv2.putText(black_sheet,'Hi', (90,300), cv2.FONT_HERSHEY_SIMPLEX, 12, (2,3,0), 2)

cv2.imshow('Text', black_sheet)
cv2.waitKey()
cv2.destroyAllWindows()